[global]
SEARCH = Ctrl+F
BACKSPACE = Ctrl+H
BACKSPACE = 127
ENTER = Ctrl+M
FILE_MANAGER = Ctrl+E
WINDOW_MANAGER = 0

[tabs]
NEXT_TAB = Ctrl+T

[insert-mode]
COPY = Ctrl+C
PASTE = Ctrl+V
CUT = Ctrl+X
SAVE = Ctrl+S

[edit-mode]

[file-manager]
PARENT_DIRECTORY = /
RENAME = r
EDIT = e
